### ISSUE TITLE
Add validation for almost right angles

### ISSUE THREAD

**Issue by marxin** [qeef/josm-scripts#12]
It would be nice to add validation filter for such buildings and also having a generic "square" command that will square just corners in a given "almost" right angle. Having possibility to setup range would be also nice ;)

**Comment by marxin** [comment]
Small motivation for such validation (task with very many buildings):
http://tasks.hotosm.org/project/3357#task/2338

Looks it uses a domain specific language (or rules):
https://josm.openstreetmap.de/wiki/Rules
https://josm.openstreetmap.de/wiki/Help/Preferences/Validator

**Comment by marxin** [comment]
I've spend recently some time with validation of few hundreds of tasks and I see following validation results as very useful:
- buildings outside a residential area (or sharing a point)
- buildings sharing a point
- validation that will show all non-circular and non-orthogonalized buildings
- groups of buildings not being in a residential area

Thanks

**Comment by qeef** [comment]
I think that I do not understand the assignment. These will be the multiple scripts?

**Comment by marxin** [comment]
Can be multiple scripts, or can have a settings. Choose what would be easier to implement.

**Comment by qeef** [comment]
> Choose what would be easier to implement.
I am sure that multiple scripts would be better way. I do not have experience with JOSM plugin development that could be more eligible.

I made a little bit of research and maybe [BuildingGeneralization plugin](https://josm.openstreetmap.de/wiki/Plugins) is way to go.

Also it would be great idea to ask @Piskvor becase he has definitely greater overview.

**Comment by Piskvor** [comment]
On 11/08/17 17:08, Jiri Hubacek wrote:
>     Choose what would be easier to implement.
>     I am sure that multiple scripts would be better way. I do not have
>     experience with JOSM plugin development that could be more eligible.
>
> I made a little bit of research and maybe BuildingGeneralization plugin
> <https://josm.openstreetmap.de/wiki/Plugins> is way to go.
>
IMHO multiple scripts.

**Comment by qeef** [comment]
Will be released in next version of JOSM, see https://josm.openstreetmap.de/ticket/16189.
