### ISSUE TITLE
Simplify shape of residential area

### ISSUE THREAD

**Issue by marxin** [qeef/josm-scripts#13]
![screenshot from 2017-09-28 21-36-18](https://user-images.githubusercontent.com/2658545/30986948-84f5bda4-a495-11e7-9a2a-0712fd514b4f.png)

As seen in the screenshot, having a circular building can create residential area with very many points close to a corner. In that case (many points close each other), I would simplify the shape.
Thanks.

**Comment by qeef** [comment]
This is tricky issue. Algorithm used is [Graham scan] [[1]] that ensure generality. The input to this algorithm is *all selected nodes* that is easy.

Solution would be to filter all input nodes that are part of circle building (all ways that are circle buildings). These nodes would be replaced by four nodes of outer rectangle that fits to circle building. 

[Graham scan]: https://github.com/qeef/josm-scripts/blob/436968fd269aac83222e2e5ba59703d031b12b55/pick_residential.js#L24
[1]: https://en.wikipedia.org/wiki/Graham_scan

**Comment by marxin** [comment]
Another solution would be to create a boundary as you do it now. And then filter out the most closest points and verify if all buildings in area still fit in area. I think it can handle very many cases this simple approach.

**Comment by qeef** [comment]
Finally I implemented building bordering - 4 nodes per building and run Graham scan for these bordering nodes.

If you have a spare time @marxin review and testing is greatly appreticiated, thanks a lot!

Anyway, I am a little bit sceptical about your proposal for problem solution:
> filter out the most closest points
How is *closest* defined? How far is close enough?
> verify if all buildings in area still fit in area
I do not have any idea how to check this. Have you? All info are GPS coordinates...

**Comment by qeef** [comment]
Just updated the #17 once more yet.

**Comment by qeef** [comment]
I tested #17 yesterday. Residential areas looks better even it is not perfect. Anyway, I think that #17 resolves this issue.

**Comment by marxin** [comment]
Looks good, thanks! Feel free to close it.
