### ISSUE TITLE
Pick Residential does not work for me

### ISSUE THREAD

**Issue by marxin** [qeef/josm-scripts#15]
After update, for some reason, this is not working. Can you please add some debugging output (logging to a console or so) in order to help me?

Thanks

**Comment by qeef** [comment]
Hi @marxin, please check shortcut settings. After [v0.1.0](https://github.com/qeef/josm-scripts/releases/tag/v0.1.0) there is a change in naming.

**Comment by marxin** [comment]
Yes, that was it. Strange that Easy Residential was still sitting in my Shortcuts preferences.
